#!/usr/bin/env bash
# script display DNS information

# display Function
display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print (length > 0) ? "A" : "CNAME"}')
    local dest=$(dig +short "$subdomain.$domain")

    echo "The subdomain $subdomain is a $record_type record and points to $dest"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    display_info "$domain" "$subdomain"
fi
