#!/usr/bin/env bash
#install and configure Nginx in server 
#update the package
sudo apt-get update

#install Nginx with yes 
sudo apt-get -y install nginx

#configure Nginx 
sudo sed -i 's/80 default_server/80 default_server/g' /etc/nginx/sites-available/default

#Restart the Nginx  with out systemctl
sudo service nginx restart

#create html file by first creating thecta directory
sudo mkdir -p /var/www/html
#take ownership
sudo chown -R $USER:$USER /var/www/html
echo "Hello World!" > /var/www/html/index.html

# NGINX configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Backup NGINX configuration file
sudo cp "$nginx_conf" "$nginx_conf.backup"

# append redirection configuration to NGINX configuration file
sudo sed -i '/server_name _;/a\\tlocation /redirect_me {\n            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' "$nginx_conf"

# Test NGINX configuration 
sudo nginx -t

#reload NGINX
sudo systemctl reload nginx
