#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
#update the package
sudo apt-get update

#install apt-get install haproxy=2.0 
sudo apt-get install haproxy=2.0.\*

# haproxy configuration file path
haproxy_conf="/etc/haproxy/haproxy.cfg"

# Backup haproxy configuration file
sudo cp "$haproxy_conf" "$haproxy_conf.backup"

#append the configuration 
frontend_backend_sections='
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 123058092-web-01 54.157.179.66:80 check
    server 123058092-web-02 100.25.35.151:80 check
'
echo "$frontend_backend_sections" | sudo tee -a /etc/haproxy/haproxy.cfg

#make it init
sudo systemctl enable haproxy

#restart
sudo systemctl restart haproxy
