#!/usr/bin/env bash
#Transfers  files from client to server
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file_path=$1
	server_ip=$2
	username=$3
	path_to_ssh_key=$4

    scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$file_path" "$username@$server_ip":~/
fi
